### ISSUE TITLE
Make IEntityTagStore and ICacheStore Signatures Task Returning

### ISSUE THREAD

**Issue by tugberkugurlu** [aliostad/CacheCow#15]
Currently, `IEntityTagStore` and `ICacheStore` provide us to create synchronous stores. Methods of these interfaces should be `Task` returning so that they can be async or sync depending on the case. If we are making synchronous calls, we can just return a pre-completed `Task` objects. This way, there will be no overhead.

**Comment by rbeauchamp-lendingtree** [comment]
I'm willing to work on this. I would upgrade the .NET version in all the projects to 4.5.2. Thoughts?

**Comment by rbeauchamp-lendingtree** [comment]
Please assign to me. I'm working on this now.

**Comment by aliostad** [comment]
Hi @rbeauchamp-lendingtree unfortunately not able to lose support for 4.0 as many clients still use 4.0/

**Comment by rbeauchamp-lendingtree** [comment]
@aliostad Not sure I understand. Are you saying that you don't want this implemented? Or if it is implemented, it needs to be done in .NET 4.0? How about a separate .NET 4.5 async build? Or just keep 4.0 clients on the old version and move on. Seems like for an ASP.NET Web API HTTP library, at some point you have to support async; this is an issue that's been open since Jan 2013. (And you have someone who is volunteering to do the hard work. It's a huge change!)

**Comment by aliostad** [comment]
A separate async build means supporting two different codebases and is a lot of work. It is kinda forking in a different direction. However, it would be nice to support.

So can you please outline your plan?

**Comment by rbeauchamp-lendingtree** [comment]
I would support either of these plans:

1. Upgrade to .NET 4.5, change the interfaces, and merge into a single code base. The older .NET 4.0 sync versions would be available via Nuget but not supported.

2.  Upgrade to .NET 4.5, change the interfaces, and commit to a separate branch which generates *.Async Nuget packages. Two codebases would be maintained producing a total 44 Nuget packages for the project.

@aliostad Since you are the repo owner, I'll leave the decision up to you.

**Comment by aliostad** [comment]
Thank you @rbeauchamp-lendingtree for volunteering.

The support of .NET 4.0 in CacheCow has been really important (and I suffered by writing async code in 4.0 with no async/await) but I think with vNext already on the horizon, **we should drop it and move on.**

So option 1 is the favourite.  And this would be the v2.0. The nuget can stay as it is.

The work would entail:

 - simplifying ContinueWith() codes to async/await
 - removing parts of the code which I am offloading where async meets sync (serialisation/deserialisation)
 - Updating all storages

Can you please confirm you are happy with this?
