### ISSUE TITLE
Question: How to implement caching with Paging from Sql Server

### ISSUE THREAD

**Issue by mintyfusion** [aliostad/CacheCow#206]
I have been going through samples and would like to understand how does the `GetMaxLastModified` work with Paging and Sql Server?

Is it that the same query is repeated and checked if the ETag has been modified? In addition, we have a React client and would it have to manage different ETag per paged query and based on page, send the associated ETag?

**Comment by aliostad** [comment]
Hi,

Yes. However, with paging, I guess you need Count, Max(LastModified) and Min(LastModified) to build the ETag, since an item in the middle of the list might be removed and Max(LastModified) will stay the same but Min(LastModified) will be different. So I suggest for your SQL Server query:

``` SQL
SELECT COUNT(1),  Max(LastModified), Min(LastModified)
  FROM dbo.[some_table]
  ORDER BY [some_column_or_columns] 
  OFFSET @PageSize * (@PageNumber - 1) ROWS
  FETCH NEXT @PageSize ROWS ONLY;
```

and bin-pack the count (4 bytes), max (10 bytes) and min (10 bytes) and represent as base64 or if there is a security consideration, hash it and then represent as base64.

**Comment by mintyfusion** [comment]
Thank You very much, it's really helpful. One another quick question, as our data is stored in Sql Server, how should we manage ETag for single objects? 

Do we query and get the whole object and then figure out ETag or just do the query to get LastUpdatedTime and if necessary make another query to get the whole object?

**Comment by aliostad** [comment]
Hi,

It is up to you and your case really. Depends on the likelihood of a cache miss and cost of getting LastUpdate or the whole thing.

If you think going to database twice is more expensive, your best bet is not to supply any `ITimedETagQueryProvide`r and instead either supply `ITimedETagExtractor` or implement `ICacheResource`  on your viewmodel.

**Comment by mintyfusion** [comment]
Thank  you very much.
