### ISSUE TITLE
Is Cachecow.Client.Filestore still supported?

### ISSUE THREAD

**Issue by pietervdvn** [aliostad/CacheCow#219]
When using FileStore 1.0.0 in combination with Client 2.4, I can't build. The error message reads `Reference to type 'ICacheMetadataProvider' claims it is defined in 'CacheCow.Client', but it could not be found`

**Comment by aliostad** [comment]
I am afraid not supported anymore. There are some blog posts that explain the recent changes.
Having said that, I am happy to accept Pull Request if you build File-based client.
http://byterot.blogspot.com/2018/05/cachecowclient-20-http-caching-for-your-api-http-httpclient-caching-cachecow-etag-dotnetcore-aspnetcore.html

**Comment by aliostad** [comment]
Let me know if you still want to discuss, otherwise closing the issue. Cheers

**Comment by pietervdvn** [comment]
Alright. Where can I find the source?

**Comment by aliostad** [comment]
They have been removed. But you can find them in other branches or if you go back in multiple commits. The work is not really that complex and it is now even simpler since the interface have simplified. In the past I had in mind to define cache sizes per domain but that proved to be both complex and not a feature wanted by people.

**Comment by pietervdvn** [comment]
See #220
