### ISSUE TITLE
Exception on Startup

### ISSUE THREAD

**Issue by duduccosta** [aliostad/CacheCow#297]
Hello.

I'm getting the follow error:

`Error while validating the service descriptor 'ServiceType: CacheCow.Server.ICachingPipeline Lifetime: Transient ImplementationType: CacheCow.Server.CachingPipeline': Unable to resolve service for type 'CacheCow.Server.HttpCachingOptions' while attempting to activate 'CacheCow.Server.CachingPipeline'.`
 `Unable to resolve service for type 'CacheCow.Server.HttpCachingOptions' while attempting to activate 'CacheCow.Server.CachingPipeline'.`

I'm using CacheCow.Server.WebApi 2.13.1.
.NET Version = 7

Occours at: 
`services.AddTransient<ICachingPipeline, CachingPipeline>();`

Using AddHttpCaching():
![image](https://github.com/aliostad/CacheCow/assets/69438711/082b7ffd-e6fc-48e3-9fea-8d0a13ec4705)

Controller:
![image](https://github.com/aliostad/CacheCow/assets/69438711/f6a5f443-e687-4ac0-9eae-4a34c3424c28)

Thanks.

**Comment by aliostad** [comment]
Hi Thanks for raising this. I will look into it.

**Comment by aliostad** [comment]
Sorry for the delay I did not have visual studio (I lost motherboard and sent for replace) but now I got it.

**Comment by aliostad** [comment]
OK, it seems that you have not configured the service in any way.

You need to consider options you wanna take and based on that provide implementations.

But since you are using Core MVC flavour rather than the classic Web API, **you just need to use** `AddHttpCachingMvc()` rather than `AddHttpCaching()` which is for the classic case. 

If you fairly new to .NET space, before there was Core MVC Web API, there was a Web API and `AddHttpCaching()` is intended for that.

If you come across other problems let me know.
